/** OAuth providers supported by the shared authorization-code + PKCE flow.
 * Each provider still needs its own client credentials in the deployment environment.
 * Scopes are intentionally minimal; provider review/approval may be required.
 */
export type OAuthProvider = { id: string; label: string; authorizeUrl: string; tokenUrl: string; clientIdEnv: string; clientSecretEnv: string; scopes: string[]; apiBase: string; apiHost: string; note: string };
const googleScopes = ["openid", "email", "profile", "https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/calendar.events.readonly", "https://www.googleapis.com/auth/gmail.readonly"];
export const OAUTH_PROVIDERS: OAuthProvider[] = [
  { id:"google", label:"Google Workspace", authorizeUrl:"https://accounts.google.com/o/oauth2/v2/auth", tokenUrl:"https://oauth2.googleapis.com/token", clientIdEnv:"GOOGLE_CLIENT_ID", clientSecretEnv:"GOOGLE_CLIENT_SECRET", scopes:googleScopes, apiBase:"https://www.googleapis.com", apiHost:"www.googleapis.com", note:"Gmail, Drive, Calendar, Sheets and Docs where granted scopes and APIs permit." },
  { id:"microsoft", label:"Microsoft 365", authorizeUrl:"https://login.microsoftonline.com/common/oauth2/v2.0/authorize", tokenUrl:"https://login.microsoftonline.com/common/oauth2/v2.0/token", clientIdEnv:"MICROSOFT_CLIENT_ID", clientSecretEnv:"MICROSOFT_CLIENT_SECRET", scopes:["openid","profile","email","offline_access","User.Read","Mail.Read","Files.Read","Calendars.Read"], apiBase:"https://graph.microsoft.com/v1.0", apiHost:"graph.microsoft.com", note:"Outlook, OneDrive, Calendar and profile APIs with granted Microsoft Graph permissions." },
  { id:"slack", label:"Slack", authorizeUrl:"https://slack.com/oauth/v2/authorize", tokenUrl:"https://slack.com/api/oauth.v2.access", clientIdEnv:"SLACK_CLIENT_ID", clientSecretEnv:"SLACK_CLIENT_SECRET", scopes:["channels:read","chat:write","users:read","search:read"], apiBase:"https://slack.com/api", apiHost:"slack.com", note:"Workspace access depends on the scopes approved by the Slack administrator." },
  { id:"github_oauth", label:"GitHub", authorizeUrl:"https://github.com/login/oauth/authorize", tokenUrl:"https://github.com/login/oauth/access_token", clientIdEnv:"GITHUB_OAUTH_CLIENT_ID", clientSecretEnv:"GITHUB_OAUTH_CLIENT_SECRET", scopes:["read:user","repo"], apiBase:"https://api.github.com", apiHost:"api.github.com", note:"Repository scopes can be broad; create a least-privilege GitHub App for production." },
  { id:"notion_oauth", label:"Notion", authorizeUrl:"https://api.notion.com/v1/oauth/authorize", tokenUrl:"https://api.notion.com/v1/oauth/token", clientIdEnv:"NOTION_OAUTH_CLIENT_ID", clientSecretEnv:"NOTION_OAUTH_CLIENT_SECRET", scopes:[], apiBase:"https://api.notion.com/v1", apiHost:"api.notion.com", note:"Notion OAuth integrations must be created and approved in the Notion developer portal." },
  { id:"linear", label:"Linear", authorizeUrl:"https://linear.app/oauth/authorize", tokenUrl:"https://api.linear.app/oauth/token", clientIdEnv:"LINEAR_CLIENT_ID", clientSecretEnv:"LINEAR_CLIENT_SECRET", scopes:["read","write"], apiBase:"https://api.linear.app", apiHost:"api.linear.app", note:"Linear GraphQL API; scopes and OAuth app settings must match the registered app." },
  { id:"dropbox", label:"Dropbox", authorizeUrl:"https://www.dropbox.com/oauth2/authorize", tokenUrl:"https://api.dropboxapi.com/oauth2/token", clientIdEnv:"DROPBOX_CLIENT_ID", clientSecretEnv:"DROPBOX_CLIENT_SECRET", scopes:[], apiBase:"https://api.dropboxapi.com/2", apiHost:"api.dropboxapi.com", note:"Enable required scopes in the Dropbox app console." },
  { id:"hubspot", label:"HubSpot", authorizeUrl:"https://app.hubspot.com/oauth/authorize", tokenUrl:"https://api.hubapi.com/oauth/v1/token", clientIdEnv:"HUBSPOT_CLIENT_ID", clientSecretEnv:"HUBSPOT_CLIENT_SECRET", scopes:["oauth","crm.objects.contacts.read","crm.objects.companies.read","crm.objects.deals.read"], apiBase:"https://api.hubapi.com", apiHost:"api.hubapi.com", note:"CRM access is limited to scopes enabled for your HubSpot app." },
  { id:"asana", label:"Asana", authorizeUrl:"https://app.asana.com/-/oauth_authorize", tokenUrl:"https://app.asana.com/-/oauth_token", clientIdEnv:"ASANA_CLIENT_ID", clientSecretEnv:"ASANA_CLIENT_SECRET", scopes:["default"], apiBase:"https://app.asana.com/api/1.0", apiHost:"app.asana.com", note:"Asana API permissions are determined by the registered app and granted account access." },
  { id:"salesforce", label:"Salesforce", authorizeUrl:"https://login.salesforce.com/services/oauth2/authorize", tokenUrl:"https://login.salesforce.com/services/oauth2/token", clientIdEnv:"SALESFORCE_CLIENT_ID", clientSecretEnv:"SALESFORCE_CLIENT_SECRET", scopes:["api","refresh_token","openid"], apiBase:"https://login.salesforce.com/services/data", apiHost:"login.salesforce.com", note:"Production or sandbox domain and connected-app policy may require provider-specific configuration." },
  { id:"zoom", label:"Zoom", authorizeUrl:"https://zoom.us/oauth/authorize", tokenUrl:"https://zoom.us/oauth/token", clientIdEnv:"ZOOM_CLIENT_ID", clientSecretEnv:"ZOOM_CLIENT_SECRET", scopes:["user:read:user"], apiBase:"https://api.zoom.us/v2", apiHost:"api.zoom.us", note:"Zoom scopes depend on the Marketplace app type and review status." },
  { id:"figma", label:"Figma", authorizeUrl:"https://www.figma.com/oauth", tokenUrl:"https://api.figma.com/v1/oauth/token", clientIdEnv:"FIGMA_CLIENT_ID", clientSecretEnv:"FIGMA_CLIENT_SECRET", scopes:["file_read"], apiBase:"https://api.figma.com/v1", apiHost:"api.figma.com", note:"Figma API permissions are restricted to scopes granted by the user and app." },
  { id:"atlassian", label:"Atlassian (Jira/Confluence)", authorizeUrl:"https://auth.atlassian.com/authorize", tokenUrl:"https://auth.atlassian.com/oauth/token", clientIdEnv:"ATLASSIAN_CLIENT_ID", clientSecretEnv:"ATLASSIAN_CLIENT_SECRET", scopes:["read:jira-work","read:jira-user","read:confluence-content.all","offline_access"], apiBase:"https://api.atlassian.com", apiHost:"api.atlassian.com", note:"Atlassian APIs often require cloudId discovery and granular scopes." },
  { id:"twitch", label:"Twitch", authorizeUrl:"https://id.twitch.tv/oauth2/authorize", tokenUrl:"https://id.twitch.tv/oauth2/token", clientIdEnv:"TWITCH_CLIENT_ID", clientSecretEnv:"TWITCH_CLIENT_SECRET", scopes:["user:read:email"], apiBase:"https://api.twitch.tv/helix", apiHost:"api.twitch.tv", note:"Twitch API requests also require the registered client ID header." },
  { id:"spotify", label:"Spotify", authorizeUrl:"https://accounts.spotify.com/authorize", tokenUrl:"https://accounts.spotify.com/api/token", clientIdEnv:"SPOTIFY_CLIENT_ID", clientSecretEnv:"SPOTIFY_CLIENT_SECRET", scopes:["user-read-private","user-read-email","playlist-read-private"], apiBase:"https://api.spotify.com/v1", apiHost:"api.spotify.com", note:"Some Spotify scopes/features require extended quota approval." },
  { id:"webflow", label:"Webflow", authorizeUrl:"https://webflow.com/oauth/authorize", tokenUrl:"https://api.webflow.com/oauth/access_token", clientIdEnv:"WEBFLOW_CLIENT_ID", clientSecretEnv:"WEBFLOW_CLIENT_SECRET", scopes:["sites:read","pages:read"], apiBase:"https://api.webflow.com/v2", apiHost:"api.webflow.com", note:"Site-specific permissions and API access depend on the Webflow app configuration." },
  { id:"wordpress", label:"WordPress.com", authorizeUrl:"https://public-api.wordpress.com/oauth2/authorize", tokenUrl:"https://public-api.wordpress.com/oauth2/token", clientIdEnv:"WORDPRESS_CLIENT_ID", clientSecretEnv:"WORDPRESS_CLIENT_SECRET", scopes:["global"], apiBase:"https://public-api.wordpress.com/rest/v1.1", apiHost:"public-api.wordpress.com", note:"Self-hosted WordPress sites may need Application Passwords or a custom OAuth plugin instead." },
  { id:"shopify", label:"Shopify", authorizeUrl:"https://shopify.com/admin/oauth/authorize", tokenUrl:"https://shopify.com/admin/oauth/access_token", clientIdEnv:"SHOPIFY_CLIENT_ID", clientSecretEnv:"SHOPIFY_CLIENT_SECRET", scopes:["read_products","read_orders","read_customers"], apiBase:"https://shopify.com/admin/api", apiHost:"shopify.com", note:"Shopify OAuth is shop-domain and app-type specific; install flow needs shop-aware configuration." },
  { id:"mailchimp", label:"Mailchimp", authorizeUrl:"https://login.mailchimp.com/oauth2/authorize", tokenUrl:"https://login.mailchimp.com/oauth2/token", clientIdEnv:"MAILCHIMP_CLIENT_ID", clientSecretEnv:"MAILCHIMP_CLIENT_SECRET", scopes:[], apiBase:"https://login.mailchimp.com", apiHost:"login.mailchimp.com", note:"Mailchimp API base URL must be discovered from metadata after authorization." },
  { id:"discord", label:"Discord", authorizeUrl:"https://discord.com/oauth2/authorize", tokenUrl:"https://discord.com/api/oauth2/token", clientIdEnv:"DISCORD_CLIENT_ID", clientSecretEnv:"DISCORD_CLIENT_SECRET", scopes:["identify","guilds"], apiBase:"https://discord.com/api/v10", apiHost:"discord.com", note:"Bot actions and user OAuth are different flows; this user OAuth flow does not create a bot." },
];
export const getOAuthProvider = (id: string) => OAUTH_PROVIDERS.find(p => p.id === id);
